upd make files for updated code
Signed-off-by: Maxim Kovgan <makovgan@redhat.com>

diff --git a/playbooks/cnf/reporting/Makefile b/playbooks/cnf/reporting/Makefile
--- a/playbooks/cnf/reporting/Makefile
+++ b/playbooks/cnf/reporting/Makefile
@@ -13,12 +13,11 @@ SRC_REQS = $(shell git rev-parse --show-toplevel)/$(DST_REQS)
 APPS = $(PY) ansible-playbook ansible-galaxy yq diff
 APPS_DEV := $(APPS) pylint ansible-lint shellcheck
 KEEP_ARTIFACTS ?= false
-
 CLEANUP_LIST := $(ANSIBLE_COLLECTIONS_PATH) $(CACHE_PATHS)	$(HOME)/.ansible/collections
 
 .ONESHELL:
 .DEFAULT_TARGETS: bootstrap
-.PHONY: make-requirements print_vars
+.PHONY: check-requirements
 
 check-requirements:
 	@APPS=($(APPS))
@@ -30,31 +29,23 @@ check-requirements:
 
 reset-collections-reqs:
 	$(MAKE) check-requirements
-	@echo "DEL_COLLECTIONS: $(DEL_COLLECTIONS)"
-	$(WRAPPER) "$@" $(SRC_REQS) $(DEL_COLLECTIONS) $(DST_REQS)
+	@if echo "$(COLLECTION_REQ_FILES_TXT)" | grep -q ","; then
+		@echo "DEL_COLLECTIONS: $(DEL_COLLECTIONS)"
+		$(WRAPPER) "$@" $(SRC_REQS) $(DEL_COLLECTIONS) $(DST_REQS)
+	@fi
 
 clean-caches:	$(CLEANUP_LIST)
 	@rm -fr "$^"
 
-buildpkg:
-	$(MAKE) reset-collections-reqs
-	$(MAKE) clean-caches
-	@export COLLECTION_ROOT=$(COLLECTION_ROOT)
-	@$(WRAPPER) "${@}"
-
 bootstrap:
 	@if [[ "$(RECREATE)" -gt 0 ]]; then
-		@SUB_TARGET="buildpkg"
-		@echo "Launching target $${SUB_TARGET}"
-		$(MAKE) $${SUB_TARGET}
-		rc=$$?
-		@echo "Finished  target: $${SUB_TARGET} with rc=$${rc}"
+		@$(MAKE) clean-caches
 	@fi
 	@export COLLECTION_REQ_FILES_TXT="$(COLLECTION_REQ_FILES_TXT)"
 	@$(WRAPPER) $@
 
 gendata:
-	@$(WRAPPER) $@
+	@$(WRAPPER) $@ || ""
 
 render:
 	@$(WRAPPER) $@
@@ -76,27 +67,31 @@ lint:	pylint	ansible-lint shellcheck
 pytest:
 	@pytest -v ./tools
 
+test-verify:
+	@echo "DEBUG: running $@ with: RAW_ACTUAL_EVENT=$(RAW_ACTUAL_EVENT), ACTUAL_EVENT=$(ACTUAL_EVENT), EXPECTED_EVENT=$(EXPECTED_EVENT)"
+	@cat $(RAW_ACTUAL_EVENT) | jq > $(ACTUAL_EVENT)
+	@if ! diff --color --unified $(EXPECTED_EVENT) $(ACTUAL_EVENT); then
+		@rc=$$?
+		@echo "test for ci=$(CI_TYPE) failed with rc=$${rc}"
+		@echo "ACTION ITEMS: review the formatted event $(ACTUAL_EVENT) and compare it to $(EXPECTED_EVENT)"
+		@exit "$${rc}"
+	@fi
+	@echo "test for $(CI_TYPE) have passed."
+	@if [[ "$(KEEP_ARTIFACTS)" -gt 0 ]]; then
+		@echo "Keeping artifacts. [REASON: KEEP_ARTIFACTS=$(KEEP_ARTIFACTS)]"
+		@exit 0
+	@fi
+	@rm $(RAW_ACTUAL_EVENT) $(ACTUAL_EVENT)
+	@echo "Deleted $(RAW_ACTUAL_EVENT) and $(ACTUAL_EVENT). [REASON: KEEP_ARTIFACTS=$(KEEP_ARTIFACTS)]"
+
 test:
 	@echo "ANSIBLE_COLLECTIONS_PATH='$(ANSIBLE_COLLECTIONS_PATH)'"
 	@$(WRAPPER) $@
-	@EXPECTED_EVENT=$(PWD)/fixtures/$(TEST)/event.json
-	@ACTUAL_EVENT=$(PWD)/curr.event.json
-	@cat $(PWD)/event.json | jq > $${ACTUAL_EVENT}
-	@if ! diff --color --unified $${EXPECTED_EVENT} $${ACTUAL_EVENT}; then
-		rc=$$?
-		echo "test for $(TEST) failed with rc=$${rc}"
-		echo "ACTION ITEMS: review the formatted event $${ACTUAL_EVENT} and compare it to $${EXPECTED_EVENT}"
-		exit "$${rc}"
-	fi
-	@echo "test for $(TEST) passed."
-	if [[ "$${KEEP_ARTIFACTS}" -gt 0 ]]; then
-		echo "Keeping artifacts. [REASON: KEEP_ARTIFACTS=$${KEEP_ARTIFACTS}]"
-		exit 0
-	fi
-	@echo "Deleting artifacts. [REASON: KEEP_ARTIFACTS=$${KEEP_ARTIFACTS}]"
-	rm $(PWD)/*event.json
+	$(eval EXPECTED_EVENT = $(PWD)/fixtures/$(CI_TYPE)/event.json)
+	$(eval ACTUAL_EVENT = $(PWD)/curr.event.json)
+	$(eval RAW_ACTUAL_EVENT = $(PWD)/event.json)
+	$(MAKE) test-verify EXPECTED_EVENT=$(EXPECTED_EVENT) ACTUAL_EVENT=$(ACTUAL_EVENT) RAW_ACTUAL_EVENT=$(RAW_ACTUAL_EVENT)
 
 retest:
-	$(MAKE) rebuild
 	$(MAKE) bootstrap RECREATE=1
 	$(MAKE) test
